# SPDX-FileCopyrightText: Tim Orling
#
# SPDX-License-Identifier: Apache-2.0

---

- name: "Ensure /etc/sysusers.d exists"
  become: true
  ansible.builtin.file:
    path: /etc/sysusers.d
    state: directory

- name: "Create sd-mux-ctrl group"
  become: true
  ansible.builtin.copy:
    dest: /etc/sysusers.d/sd-mux-ctrl.conf
    content: |
      # Type	Name		ID	GECOS		Home directory Shell
      u		sd-mux-ctrl	-	"sd-mux-ctrl for SD-Wire"
  when: "not sdmuxctrl_group_is_installed"
  notify: "sdmuxctrl group has been installed"
