#SPDX-License-Identifier: Apache-2.0
---
# handlers file for ansible-role-sd-mux-ctrl

- name: "sd-mux-ctrl build dependencies have been installed"
  become: true
  ansible.builtin.set_fact:
    sdmuxctrl_build_deps_are_installed: true

- name: "sd-mux-ctrl has been cloned"
  become: true
  ansible.builtin.set_fact:
    sdmuxctrl_is_cloned: true

- name: "sd-mux-ctrl has been built"
  ansible.builtin.set_fact:
    sdmuxctrl_is_built: true
  listen: "sd-mux-ctrl has been cloned"

- name: "sd-mux-ctrl has been installed or upgraded"
  become: true
  ansible.builtin.set_fact:
    sdmuxctrl_is_upgraded: true

- name: "sd-mux-ctrl group has been installed"
  become: true
  ansible.builtin.set_fact:
    sdmuxctrl_group_is_installed: true
